### ISSUE TITLE
Is whaleclub's auth really secure? I don't see any cryptographic message digest being used.

### ISSUE THREAD

**Issue by greatwolf** [askmike/whaleclub#1]
Title's self explanatory.

From what I can tell the API literally just authenticates by having the api_key sent in the headers over the internet. How is this even secure? All the other exchange API's I've seen use some kind of HMAC or cryptographic digest as the signature, the api secret is never transmitted over the internet.

**Comment by askmike** [comment]
They only support an https endpoint, which means they rely solely on encrypting data in transit using SSL.

- They use SSL to encrypt headers & body.
- They expect you to validate the SSL cert (which nodejs does for you automatically, unless [you specifically disabled it](http://stackoverflow.com/questions/10888610/ignore-invalid-self-signed-ssl-certificate-in-node-js-with-https-request)).

Because of this no one is able to:

- Read the content of the message (content nor API key)
- Alter the content of the message.

Until something happens with SSL (or there SSL setup is wrong) this should be safe, it is unlikely that something happens, but stuff has happened in the past (examples are [POODLE](https://en.wikipedia.org/wiki/POODLE) and [DROWNATTACK](https://drownattack.com/)).
